openapi: 3.0.4
info:
  title: Express + TypeScript And GraphQL/RESTfull, AWS serverless Lambda
  description: Express + TypeScript And GraphQL/RESTfull, AWS Lambda serverless setup with industrial standard
  version: 0.0.1

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /ping:
    get:
      summary: Returns time and status
      responses:
        "200": # status code
          description: message and current time
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
components:
  schemas:
    Ping:
      type: object
      properties:
        working:
          type: string
          example: "working..."
        time:
          type: string
          format: date-time
          example: "2025-12-29T17:45:00Z"
